# coding=utf-8
language = {
    'en': 0,
    'cn': 1,
    'fr': 2,
}

lib = {
    'wave': ['Wave', '绘图器', 'Wave'],
    'waveview': ['WaveView', 'WaveView', 'WaveView'],
    'editor': ['Editor', '编辑器', 'Éditeur'],
    'editorview': ['EditorView', 'EditorView', 'EditorView'],
    'ascii': ['Ascii', '字符图', 'Ascii'],
    'asciiview': ['AsciiView', 'AsciiView', 'AsciiView'],
    'copy': ['Copy', '复制', 'Copier'],
    'new': ['New', '新建', 'Nouveau'],
    'open': ['Open', '打开', 'Ouvrir'],
    'save': ['Save', '保存', 'Enregistrer'],
    'save_as': ['Save As', '另存为', 'Enregistrer sous...'],
    'exit': ['Exit', '退出', 'Quitter'],
    'file': ['File', '文件', 'Fichier'],
    'undo': ['Undo', '撤销', 'Annuler'],
    'redo': ['Redo', '重做', 'Rétablir'],
    'add_row': ['Add Row', '增加行', 'Ajouter ligne'],
    'add_col': ['Add Column', '增加列', 'Ajouter colonne'],
    'del_row': ['Delete Row', '删除行', 'Supprimer ligne'],
    'del_col': ['Delete Column', '删除列', 'Supprimer colonne'],
    'edit': ['Edit', '编辑', 'Éditer'],
    'copy_row': ['Copy Row', '复制行', 'Copier ligne'],
    'swap_row': ['Swap Row', '调整行序', 'Échanger ligne'],
    'sig_early': ['Signal Early', '信号提前', 'Reculer signal'],
    'sig_delay': ['Signal Delay', '信号延迟', 'Avancer signal'],
    'bus_color': ['Bus Color', '总线颜色', 'Couleur bus'],
    'default': ['Default', '默认', 'Par défaut'],
    'lowkey': ['Lowkey', '黑白', 'Lowkey'],
    'narrow': ['Narrow', '紧凑', 'Narrow'],
    'skin': ['Skin', '皮肤', 'Apparence'],
    'scale': ['Scale', '缩放', 'Échelle'],
    'period': ['Period', '周期', 'Période'],
    'annotate': ['Annotate', '标注', 'Annoter'],
    'edge': ['Edge', '标注沿', 'Edge'],
    'relation': ['Relationship', '标注关系', 'Relation'],
    'add': ['Add', '增加', 'Ajouter'],
    'yes': ['Yes', '确认', 'Oui'],
    'ok': ['Ok', '关闭', 'Ok'],
    'style': ['Style', '样式', 'Style'],
    'cancel': ['Cancel', '取消', 'Annuler'],
    'display': ['Display', '显示', 'Afficher'],
    'help': ['Help', '帮助', 'Aide'],
    'doc': ['Documentation', '文档', 'Documentation'],
    'doc_wd': ['WaveDrom', 'WaveDrom', 'WaveDrom'],
    'doc_wdgen': ['WaveDromGen', 'WaveDromGen', 'WaveDromGen'],
    'language': ['Language', '语言', 'Langage'],
    'cn': ['Chinese', '中文', 'Chinois'],
    'en': ['English', '英语', 'Anglais'],
    'fr': ['French', '法国', 'Français'],
    'signal': ['Signal', '信号', 'Signal'],
    'phase': ['Phase', '相位', 'Phase'],
    'tip': ['Tip', '提示', 'Information'],
    'restart_assert': ['This change will assert after restart', '修改完成，重启生效', 'Ce changement s\'appliquera après le redémarrage'],
    'display_cursor': ['Display Cursor ', '显示光标', 'Afficher curseur'],
    'about': ['About', '关于', 'A propos'],
    'find': ['Find', '查找', 'Trouver'],
    'find_text': ['Find Text', '查找内容', 'Trouver Texte'],
    'ignore_case': ['Ignore Case', '忽略大小写', 'Ignorer la casse'],
    'match_found': ['Find %d match', '发现 %d 匹配项', '%d correspondances trouvées'],
    'settings': ['Settings', '设置', 'Paramètres'],
    'resize': ['Resize', '调整大小', 'Redimensionner'],
    'name' : ['Name', '名称', 'Nom'],
    'modify' : ['Modify', '调整', 'Modifier'],
    'delete' : ['Delete', '删除', 'Supprimer'],
    'input_error' : ['Input error', '输入错误', 'Erreur de saisie'],
    'msg_edge_error' : ['The value entered must have a length strictly equal to 1.', '输入的值的长度必须严格等于 1', 'La valeur saisie doit être d\'une longueur strictement égale à 1.'],
    'creation_error' : ['Creation error', '创建错误', 'Erreur de création'],
    'msg_existing_relation_error' : ['A relationship between these two nodes already exists.', '这两个节点之间的关系已经存在', 'Une relation entre ces deux nœuds est déjà existante.'],
    'msg_existing_node_error' : ['This node already exists.', '该节点已存在', 'Ce nœud existe déjà.'],
    'msg_creation_error': ['A relationship must contain two nodes and a relationship style.', '一个关系必须包含两个节点和一个关系样式', 'Une relation doit contenir deux noeuds et un style de relation.'],
    'management_periods_phases': ['Management of periods and phases', '时期和阶段的管理', 'Gestion des périodes et phases'],
    'apply': ['Apply', '申请', 'Appliquer'],
    'reset': ['Reset', '重置', 'Réinitialiser'],
    'msg_set_period': ['The phase of a signal must be a decimal number greater than or equal to 0 and the period of a signal must be a integer greater than or equal to 0.', '信号的相位必须是大于等于0的十进制数，信号的周期必须是大于等于0的整数', 'La phase d\'un signal doit être un nombre décimal supérieur ou égal à 0 et la période d\'un signal doit être un entier supérieur ou égal à 0.'],
}