# coding=utf-8
language = {
    'en': 0,
    'cn': 1,
}
lib = {
    'wave': ['Wave', '绘图器'],
    'editor': ['Editor', '编辑器'],
    'ascii': ['Ascii', '字符图'],
    'copy': ['Copy', '复制'],
    'new': ['New', '新建'],
    'open': ['Open', '打开'],
    'save': ['Save', '保存'],
    'save_as': ['Save As', '另存为'],
    'exit': ['Exit', '退出'],
    'file': ['File', '文件'],
    'undo': ['Undo', '撤销'],
    'redo': ['Redo', '重做'],
    'add_row': ['Add Row', '增加行'],
    'add_col': ['Add Column', '增加列'],
    'del_row': ['Delete Row', '删除行'],
    'del_col': ['Delete Column', '删除列'],
    'edit': ['Edit', '编辑'],
    'copy_row': ['Copy Row', '复制行'],
    'swap_row': ['Swap Row', '调整行序'],
    'sig_early': ['Signal Early', '信号提前'],
    'sig_delay': ['Signal Delay', '信号延迟'],
    'bus_color': ['Bus Color', '总线颜色'],
    'default': ['Default', '默认'],
    'lowkey': ['Lowkey', '黑白'],
    'narrow': ['Narrow', '紧凑'],
    'skin': ['Skin', '皮肤'],
    'scale': ['Scale', '缩放'],
    'period': ['Period', '周期'],
    'annotate': ['Annotate', '标注'],
    'edge': ['Edge', '标注沿'],
    'relation': ['Relationship', '标注关系'],
    'add': ['Add', '增加'],
    'yes': ['Yes', '确认'],
    'ok': ['Ok', '关闭'],
    'style': ['style', '样式'],
    'cancel': ['Cancel', '取消'],
    'display': ['Display', '显示'],
    'help': ['Help', '帮助'],
    'doc': ['Document', '文档'],
    'language': ['Language', '语言'],
    'cn': ['Chinese', '中文'],
    'en': ['English', '英语'],
    'signal': ['Signal', '信号'],
    'phase': ['Phase', '相位'],
    'tip': ['Tip', '提示'],
    'restart_assert': ['This change will assert after restart', '修改完成，重启生效'],
    'display_cursor': ['Display Cursor ', '显示光标'],
    'about': ['About', '关于'],
    'find': ['Find', '查找'],
    'find_text': ['Find Text', '查找内容'],
    'ignore_case': ['Ignore Case', '忽略大小写'],
    'match_found': ['Find %d match', '发现 %d 匹配项'],
}
